on:
  push:
    branches:
      # - '*'
      # - '!master'
      - "feature/*"

jobs:
  dummy:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo "Hello World from new-feature1 branch!"
